---
services:
  nautobot:
    extra_hosts:
      - "localhost:host-gateway" # Allow Nautobot to communicate with the Bot Framwork Emulator running on the host machine.
  worker:
    extra_hosts:
      - "localhost:host-gateway" # Allow Nautobot to communicate with the Bot Framwork Emulator running on the host machine.
